/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'priceInPaise' : IDL.Nat,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'imageUrl' : ExternalBlob,
  'isFeatured' : IDL.Bool,
  'category' : IDL.Text,
  'salesCount' : IDL.Nat,
  'fileUrl' : ExternalBlob,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const OrderDTO = IDL.Record({
  'id' : IDL.Nat,
  'paymentStatus' : IDL.Text,
  'productIds' : IDL.Vec(IDL.Nat),
  'createdAt' : IDL.Int,
  'cashfreeOrderId' : IDL.Text,
  'totalAmount' : IDL.Nat,
  'buyerPrincipal' : IDL.Principal,
});
export const ProductDTO = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'priceInPaise' : IDL.Nat,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'imageUrl' : IDL.Opt(IDL.Text),
  'isFeatured' : IDL.Bool,
  'category' : IDL.Text,
  'salesCount' : IDL.Nat,
  'fileUrl' : IDL.Opt(IDL.Text),
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addProduct' : IDL.Func([Product], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCashfreePaymentLink' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createOrder' : IDL.Func(
      [IDL.Vec(IDL.Nat), IDL.Nat, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'deleteProduct' : IDL.Func([IDL.Nat], [], []),
  'getAdminStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'totalProducts' : IDL.Nat,
          'totalOrders' : IDL.Nat,
          'pendingOrders' : IDL.Nat,
          'totalRevenue' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getAllOrders' : IDL.Func([], [IDL.Vec(OrderDTO)], ['query']),
  'getAllProductsByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ProductDTO)],
      ['query'],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDownloadUrl' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Opt(IDL.Text)], []),
  'getFeaturedProducts' : IDL.Func([], [IDL.Vec(ProductDTO)], ['query']),
  'getMyOrders' : IDL.Func([], [IDL.Vec(OrderDTO)], ['query']),
  'getOrder' : IDL.Func([IDL.Nat], [OrderDTO], []),
  'getProduct' : IDL.Func([IDL.Nat], [ProductDTO], ['query']),
  'getProducts' : IDL.Func([], [IDL.Vec(ProductDTO)], ['query']),
  'getTopSellers' : IDL.Func([IDL.Nat], [IDL.Vec(ProductDTO)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'searchProducts' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(ProductDTO)],
      ['query'],
    ),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updatePaymentStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'updateProduct' : IDL.Func([IDL.Nat, Product], [], []),
  'verifyPaymentStatus' : IDL.Func([IDL.Text], [IDL.Text], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'priceInPaise' : IDL.Nat,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'imageUrl' : ExternalBlob,
    'isFeatured' : IDL.Bool,
    'category' : IDL.Text,
    'salesCount' : IDL.Nat,
    'fileUrl' : ExternalBlob,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const OrderDTO = IDL.Record({
    'id' : IDL.Nat,
    'paymentStatus' : IDL.Text,
    'productIds' : IDL.Vec(IDL.Nat),
    'createdAt' : IDL.Int,
    'cashfreeOrderId' : IDL.Text,
    'totalAmount' : IDL.Nat,
    'buyerPrincipal' : IDL.Principal,
  });
  const ProductDTO = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'priceInPaise' : IDL.Nat,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'imageUrl' : IDL.Opt(IDL.Text),
    'isFeatured' : IDL.Bool,
    'category' : IDL.Text,
    'salesCount' : IDL.Nat,
    'fileUrl' : IDL.Opt(IDL.Text),
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addProduct' : IDL.Func([Product], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCashfreePaymentLink' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createOrder' : IDL.Func(
        [IDL.Vec(IDL.Nat), IDL.Nat, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'deleteProduct' : IDL.Func([IDL.Nat], [], []),
    'getAdminStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'totalProducts' : IDL.Nat,
            'totalOrders' : IDL.Nat,
            'pendingOrders' : IDL.Nat,
            'totalRevenue' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getAllOrders' : IDL.Func([], [IDL.Vec(OrderDTO)], ['query']),
    'getAllProductsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ProductDTO)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDownloadUrl' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Opt(IDL.Text)], []),
    'getFeaturedProducts' : IDL.Func([], [IDL.Vec(ProductDTO)], ['query']),
    'getMyOrders' : IDL.Func([], [IDL.Vec(OrderDTO)], ['query']),
    'getOrder' : IDL.Func([IDL.Nat], [OrderDTO], []),
    'getProduct' : IDL.Func([IDL.Nat], [ProductDTO], ['query']),
    'getProducts' : IDL.Func([], [IDL.Vec(ProductDTO)], ['query']),
    'getTopSellers' : IDL.Func([IDL.Nat], [IDL.Vec(ProductDTO)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'searchProducts' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(ProductDTO)],
        ['query'],
      ),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updatePaymentStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'updateProduct' : IDL.Func([IDL.Nat, Product], [], []),
    'verifyPaymentStatus' : IDL.Func([IDL.Text], [IDL.Text], []),
  });
};

export const init = ({ IDL }) => { return []; };