/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export interface OrderDTO {
  'id' : bigint,
  'paymentStatus' : string,
  'productIds' : Array<bigint>,
  'createdAt' : bigint,
  'cashfreeOrderId' : string,
  'totalAmount' : bigint,
  'buyerPrincipal' : Principal,
}
export interface Product {
  'id' : bigint,
  'name' : string,
  'priceInPaise' : bigint,
  'description' : string,
  'isActive' : boolean,
  'imageUrl' : ExternalBlob,
  'isFeatured' : boolean,
  'category' : string,
  'salesCount' : bigint,
  'fileUrl' : ExternalBlob,
}
export interface ProductDTO {
  'id' : bigint,
  'name' : string,
  'priceInPaise' : bigint,
  'description' : string,
  'isActive' : boolean,
  'imageUrl' : [] | [string],
  'isFeatured' : boolean,
  'category' : string,
  'salesCount' : bigint,
  'fileUrl' : [] | [string],
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addProduct' : ActorMethod<[Product], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCashfreePaymentLink' : ActorMethod<
    [bigint, bigint, string, string],
    string
  >,
  'createOrder' : ActorMethod<[Array<bigint>, bigint, string], bigint>,
  'deleteProduct' : ActorMethod<[bigint], undefined>,
  'getAdminStats' : ActorMethod<
    [],
    {
      'totalProducts' : bigint,
      'totalOrders' : bigint,
      'pendingOrders' : bigint,
      'totalRevenue' : bigint,
    }
  >,
  'getAllOrders' : ActorMethod<[], Array<OrderDTO>>,
  'getAllProductsByCategory' : ActorMethod<[string], Array<ProductDTO>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDownloadUrl' : ActorMethod<[bigint, bigint], [] | [string]>,
  'getFeaturedProducts' : ActorMethod<[], Array<ProductDTO>>,
  'getMyOrders' : ActorMethod<[], Array<OrderDTO>>,
  'getOrder' : ActorMethod<[bigint], OrderDTO>,
  'getProduct' : ActorMethod<[bigint], ProductDTO>,
  'getProducts' : ActorMethod<[], Array<ProductDTO>>,
  'getTopSellers' : ActorMethod<[bigint], Array<ProductDTO>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'searchProducts' : ActorMethod<[string, string], Array<ProductDTO>>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updatePaymentStatus' : ActorMethod<[bigint, string], undefined>,
  'updateProduct' : ActorMethod<[bigint, Product], undefined>,
  'verifyPaymentStatus' : ActorMethod<[string], string>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];